import 'package:json_annotation/json_annotation.dart';

part 'master_feelings_dto.g.dart'; // This file is generated by running 'flutter pub run build_runner build'

@JsonSerializable()
class MasterFeelingDto {
  final String slug;
  final String name;
  final String description;

  @JsonKey(
      name:
          'mood_id') // This line maps the JSON key 'mood_id' to the Dart variable 'moodId'
  final int moodId;

  MasterFeelingDto({
    required this.slug,
    required this.name,
    required this.moodId,
    required this.description,
  });

  // Factory constructor for creating a new `MasterFeeling` instance from a map.
  // The `_$MasterFeelingFromJson` function is generated by `json_serializable`.
  factory MasterFeelingDto.fromJson(Map<String, dynamic> json) =>
      _$MasterFeelingDtoFromJson(json);

  // Method for converting a `MasterFeeling` instance to a map.
  // The `_$MasterFeelingToJson` function is generated by `json_serializable`.
  Map<String, dynamic> toJson() => _$MasterFeelingDtoToJson(this);
}
