import 'package:json_annotation/json_annotation.dart';

part 'master_factor_dto.g.dart'; // This file is generated by running 'flutter pub run build_runner build'

@JsonSerializable()
class MasterFactorDto {
  final String slug;
  final String name;

  @JsonKey(name: 'category_id')
  final String categoryId;

  MasterFactorDto({
    required this.slug,
    required this.name,
    required this.categoryId,
  });

  factory MasterFactorDto.fromJson(Map<String, dynamic> json) =>
      _$MasterFactorDtoFromJson(json);

  Map<String, dynamic> toJson() => _$MasterFactorDtoToJson(this);
}
