import 'package:json_annotation/json_annotation.dart';
import 'master_factor_dto.dart'; // Import the MasterFactorDto

part 'master_feelings_dto.g.dart'; // This file is generated by running 'flutter pub run build_runner build'

@JsonSerializable()
class MasterFeelingDto {
  final String slug;
  final String name;
  final String description;

  @JsonKey(name: 'mood_id')
  final int moodId;

  @JsonKey(defaultValue: []) // Default to an empty list if not provided
  final List<MasterFactorDto>? factors;

  MasterFeelingDto({
    required this.slug,
    required this.name,
    required this.description,
    required this.moodId,
    required this.factors,
  });

  factory MasterFeelingDto.fromJson(Map<String, dynamic> json) =>
      _$MasterFeelingDtoFromJson(json);

  Map<String, dynamic> toJson() => _$MasterFeelingDtoToJson(this);
}
