import 'package:json_annotation/json_annotation.dart';

part 'quote_dto.g.dart'; // This file is generated by running 'flutter pub run build_runner build'

@JsonSerializable()
class QuoteDto {
  @JsonKey(name: '_id')
  final String id;
  final String author;
  final String source;
  final String text;

  @JsonKey(defaultValue: [])
  final List<String> tags;

  QuoteDto({
    required this.id,
    required this.author,
    required this.source,
    required this.text,
    required this.tags,
  });

  factory QuoteDto.fromJson(Map<String, dynamic> json) => _$QuoteDtoFromJson(json);

  Map<String, dynamic> toJson() => _$QuoteDtoToJson(this);
}
